on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 16
      uses: actions/setup-node@v2-beta
      with:
        node-version: '16'
      
    - name: 🔨 Build Project
      run: |
        unset CI
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 193.168.192.154
        username: u877982310.faisalamgir
        password: Faisal2022!
        local-dir: ./dist/
